[package]
name = "betula_egui"
version = "0.0.1"
edition = "2021"
license = "BSD-3-Clause"

# Use egui from source as the PanZoom example is really new.
[dependencies]
egui = { git = "https://github.com/emilk/egui.git", rev = "bf7ffb982a6e8c0a40d0871c38bccacef9ee8efb"}

betula_core = { workspace = true, default-features = false }

[dev-dependencies]
eframe = { git = "https://github.com/emilk/egui.git", rev = "bf7ffb982a6e8c0a40d0871c38bccacef9ee8efb"}
